name: CI RUBY
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  ruby_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Run Tests
        working-directory: ./ruby
        run: ruby customer_success_balancing.rb